#!/usr/bin/env python
# This file is part of the sos project: https://github.com/antonioromito/rhsm-api-client
#
# This copyrighted material is made available to anyone wishing to use,
# modify, copy, or redistribute it subject to the terms and conditions of
# version 2 of the GNU General Public License.
#
# See the LICENSE file in the source distribution for further information.

""" rhsm-api-client entry point. """

import sys
try:
    from .rhsm.client import main
except KeyboardInterrupt:
    raise SystemExit()

if __name__ == '__main__':
    main()

# vim: set et ts=4 sw=4 :
